/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as OSlugRouteImport } from './routes/o.$slug'
import { Route as AuthenticatedSwipeRouteImport } from './routes/_authenticated/swipe'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedScentsRouteImport } from './routes/_authenticated/scents'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedClosetIndexRouteImport } from './routes/_authenticated/closet.index'
import { Route as AuthenticatedClosetNewRouteImport } from './routes/_authenticated/closet.new'
import { Route as AuthenticatedClosetIdRouteImport } from './routes/_authenticated/closet.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OSlugRoute = OSlugRouteImport.update({
  id: '/o/$slug',
  path: '/o/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSwipeRoute = AuthenticatedSwipeRouteImport.update({
  id: '/swipe',
  path: '/swipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScentsRoute = AuthenticatedScentsRouteImport.update({
  id: '/scents',
  path: '/scents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClosetIndexRoute =
  AuthenticatedClosetIndexRouteImport.update({
    id: '/closet/',
    path: '/closet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosetNewRoute = AuthenticatedClosetNewRouteImport.update({
  id: '/closet/new',
  path: '/closet/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClosetIdRoute = AuthenticatedClosetIdRouteImport.update({
  id: '/closet/$id',
  path: '/closet/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scents': typeof AuthenticatedScentsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/swipe': typeof AuthenticatedSwipeRoute
  '/o/$slug': typeof OSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/closet/$id': typeof AuthenticatedClosetIdRoute
  '/closet/new': typeof AuthenticatedClosetNewRoute
  '/closet/': typeof AuthenticatedClosetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scents': typeof AuthenticatedScentsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/swipe': typeof AuthenticatedSwipeRoute
  '/o/$slug': typeof OSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/closet/$id': typeof AuthenticatedClosetIdRoute
  '/closet/new': typeof AuthenticatedClosetNewRoute
  '/closet': typeof AuthenticatedClosetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/scents': typeof AuthenticatedScentsRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/swipe': typeof AuthenticatedSwipeRoute
  '/o/$slug': typeof OSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/_authenticated/closet/$id': typeof AuthenticatedClosetIdRoute
  '/_authenticated/closet/new': typeof AuthenticatedClosetNewRoute
  '/_authenticated/closet/': typeof AuthenticatedClosetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/feed'
    | '/generate'
    | '/home'
    | '/profile'
    | '/scents'
    | '/shop'
    | '/swipe'
    | '/o/$slug'
    | '/u/$handle'
    | '/closet/$id'
    | '/closet/new'
    | '/closet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/feed'
    | '/generate'
    | '/home'
    | '/profile'
    | '/scents'
    | '/shop'
    | '/swipe'
    | '/o/$slug'
    | '/u/$handle'
    | '/closet/$id'
    | '/closet/new'
    | '/closet'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/feed'
    | '/_authenticated/generate'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/scents'
    | '/_authenticated/shop'
    | '/_authenticated/swipe'
    | '/o/$slug'
    | '/u/$handle'
    | '/_authenticated/closet/$id'
    | '/_authenticated/closet/new'
    | '/_authenticated/closet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  OSlugRoute: typeof OSlugRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$slug': {
      id: '/o/$slug'
      path: '/o/$slug'
      fullPath: '/o/$slug'
      preLoaderRoute: typeof OSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/swipe': {
      id: '/_authenticated/swipe'
      path: '/swipe'
      fullPath: '/swipe'
      preLoaderRoute: typeof AuthenticatedSwipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scents': {
      id: '/_authenticated/scents'
      path: '/scents'
      fullPath: '/scents'
      preLoaderRoute: typeof AuthenticatedScentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closet/': {
      id: '/_authenticated/closet/'
      path: '/closet'
      fullPath: '/closet/'
      preLoaderRoute: typeof AuthenticatedClosetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closet/new': {
      id: '/_authenticated/closet/new'
      path: '/closet/new'
      fullPath: '/closet/new'
      preLoaderRoute: typeof AuthenticatedClosetNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closet/$id': {
      id: '/_authenticated/closet/$id'
      path: '/closet/$id'
      fullPath: '/closet/$id'
      preLoaderRoute: typeof AuthenticatedClosetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScentsRoute: typeof AuthenticatedScentsRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedSwipeRoute: typeof AuthenticatedSwipeRoute
  AuthenticatedClosetIdRoute: typeof AuthenticatedClosetIdRoute
  AuthenticatedClosetNewRoute: typeof AuthenticatedClosetNewRoute
  AuthenticatedClosetIndexRoute: typeof AuthenticatedClosetIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScentsRoute: AuthenticatedScentsRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedSwipeRoute: AuthenticatedSwipeRoute,
  AuthenticatedClosetIdRoute: AuthenticatedClosetIdRoute,
  AuthenticatedClosetNewRoute: AuthenticatedClosetNewRoute,
  AuthenticatedClosetIndexRoute: AuthenticatedClosetIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  OSlugRoute: OSlugRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
