/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as OSlugRouteImport } from './routes/o.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalLocationWeatherRouteImport } from './routes/legal.location-weather'
import { Route as LegalCopyrightRouteImport } from './routes/legal.copyright'
import { Route as LegalCommunityGuidelinesRouteImport } from './routes/legal.community-guidelines'
import { Route as LegalBetaNoticeRouteImport } from './routes/legal.beta-notice'
import { Route as LegalAiImageProcessingRouteImport } from './routes/legal.ai-image-processing'
import { Route as LegalAffiliateDisclosureRouteImport } from './routes/legal.affiliate-disclosure'
import { Route as LegalAccountDeletionRouteImport } from './routes/legal.account-deletion'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal.acceptable-use'
import { Route as AuthResetPasswordRouteImport } from './routes/auth_.reset-password'
import { Route as AuthenticatedTasteRouteImport } from './routes/_authenticated/taste'
import { Route as AuthenticatedSwipeRouteImport } from './routes/_authenticated/swipe'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedScentsRouteImport } from './routes/_authenticated/scents'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedInspoRouteImport } from './routes/_authenticated/inspo'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedClosetIndexRouteImport } from './routes/_authenticated/closet.index'
import { Route as AuthenticatedClosetNewRouteImport } from './routes/_authenticated/closet.new'
import { Route as AuthenticatedClosetIdRouteImport } from './routes/_authenticated/closet.$id'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin.catalog'
import { Route as AuthenticatedClosetIdEditRouteImport } from './routes/_authenticated/closet.$id.edit'
import { Route as AuthenticatedAdminCatalogImportsRouteImport } from './routes/_authenticated/admin.catalog_.imports'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OSlugRoute = OSlugRouteImport.update({
  id: '/o/$slug',
  path: '/o/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalLocationWeatherRoute = LegalLocationWeatherRouteImport.update({
  id: '/location-weather',
  path: '/location-weather',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCopyrightRoute = LegalCopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCommunityGuidelinesRoute =
  LegalCommunityGuidelinesRouteImport.update({
    id: '/community-guidelines',
    path: '/community-guidelines',
    getParentRoute: () => LegalRoute,
  } as any)
const LegalBetaNoticeRoute = LegalBetaNoticeRouteImport.update({
  id: '/beta-notice',
  path: '/beta-notice',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAiImageProcessingRoute = LegalAiImageProcessingRouteImport.update({
  id: '/ai-image-processing',
  path: '/ai-image-processing',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAffiliateDisclosureRoute =
  LegalAffiliateDisclosureRouteImport.update({
    id: '/affiliate-disclosure',
    path: '/affiliate-disclosure',
    getParentRoute: () => LegalRoute,
  } as any)
const LegalAccountDeletionRoute = LegalAccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => LegalRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth_/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasteRoute = AuthenticatedTasteRouteImport.update({
  id: '/taste',
  path: '/taste',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSwipeRoute = AuthenticatedSwipeRouteImport.update({
  id: '/swipe',
  path: '/swipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScentsRoute = AuthenticatedScentsRouteImport.update({
  id: '/scents',
  path: '/scents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspoRoute = AuthenticatedInspoRouteImport.update({
  id: '/inspo',
  path: '/inspo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClosetIndexRoute =
  AuthenticatedClosetIndexRouteImport.update({
    id: '/closet/',
    path: '/closet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosetNewRoute = AuthenticatedClosetNewRouteImport.update({
  id: '/closet/new',
  path: '/closet/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClosetIdRoute = AuthenticatedClosetIdRouteImport.update({
  id: '/closet/$id',
  path: '/closet/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/admin/moderation',
    path: '/admin/moderation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/admin/catalog',
    path: '/admin/catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosetIdEditRoute =
  AuthenticatedClosetIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedClosetIdRoute,
  } as any)
const AuthenticatedAdminCatalogImportsRoute =
  AuthenticatedAdminCatalogImportsRouteImport.update({
    id: '/admin/catalog_/imports',
    path: '/admin/catalog/imports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inspo': typeof AuthenticatedInspoRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/scents': typeof AuthenticatedScentsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/swipe': typeof AuthenticatedSwipeRoute
  '/taste': typeof AuthenticatedTasteRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/account-deletion': typeof LegalAccountDeletionRoute
  '/legal/affiliate-disclosure': typeof LegalAffiliateDisclosureRoute
  '/legal/ai-image-processing': typeof LegalAiImageProcessingRoute
  '/legal/beta-notice': typeof LegalBetaNoticeRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/copyright': typeof LegalCopyrightRoute
  '/legal/location-weather': typeof LegalLocationWeatherRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/o/$slug': typeof OSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/legal/': typeof LegalIndexRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/closet/$id': typeof AuthenticatedClosetIdRouteWithChildren
  '/closet/new': typeof AuthenticatedClosetNewRoute
  '/closet/': typeof AuthenticatedClosetIndexRoute
  '/admin/catalog/imports': typeof AuthenticatedAdminCatalogImportsRoute
  '/closet/$id/edit': typeof AuthenticatedClosetIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inspo': typeof AuthenticatedInspoRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/scents': typeof AuthenticatedScentsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/swipe': typeof AuthenticatedSwipeRoute
  '/taste': typeof AuthenticatedTasteRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/account-deletion': typeof LegalAccountDeletionRoute
  '/legal/affiliate-disclosure': typeof LegalAffiliateDisclosureRoute
  '/legal/ai-image-processing': typeof LegalAiImageProcessingRoute
  '/legal/beta-notice': typeof LegalBetaNoticeRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/copyright': typeof LegalCopyrightRoute
  '/legal/location-weather': typeof LegalLocationWeatherRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/o/$slug': typeof OSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/legal': typeof LegalIndexRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/closet/$id': typeof AuthenticatedClosetIdRouteWithChildren
  '/closet/new': typeof AuthenticatedClosetNewRoute
  '/closet': typeof AuthenticatedClosetIndexRoute
  '/admin/catalog/imports': typeof AuthenticatedAdminCatalogImportsRoute
  '/closet/$id/edit': typeof AuthenticatedClosetIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inspo': typeof AuthenticatedInspoRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/scents': typeof AuthenticatedScentsRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/swipe': typeof AuthenticatedSwipeRoute
  '/_authenticated/taste': typeof AuthenticatedTasteRoute
  '/auth_/reset-password': typeof AuthResetPasswordRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/account-deletion': typeof LegalAccountDeletionRoute
  '/legal/affiliate-disclosure': typeof LegalAffiliateDisclosureRoute
  '/legal/ai-image-processing': typeof LegalAiImageProcessingRoute
  '/legal/beta-notice': typeof LegalBetaNoticeRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/copyright': typeof LegalCopyrightRoute
  '/legal/location-weather': typeof LegalLocationWeatherRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/o/$slug': typeof OSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/legal/': typeof LegalIndexRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/closet/$id': typeof AuthenticatedClosetIdRouteWithChildren
  '/_authenticated/closet/new': typeof AuthenticatedClosetNewRoute
  '/_authenticated/closet/': typeof AuthenticatedClosetIndexRoute
  '/_authenticated/admin/catalog_/imports': typeof AuthenticatedAdminCatalogImportsRoute
  '/_authenticated/closet/$id/edit': typeof AuthenticatedClosetIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/legal'
    | '/onboarding'
    | '/feed'
    | '/generate'
    | '/home'
    | '/inspo'
    | '/profile'
    | '/saved'
    | '/scents'
    | '/shop'
    | '/swipe'
    | '/taste'
    | '/auth/reset-password'
    | '/legal/acceptable-use'
    | '/legal/account-deletion'
    | '/legal/affiliate-disclosure'
    | '/legal/ai-image-processing'
    | '/legal/beta-notice'
    | '/legal/community-guidelines'
    | '/legal/copyright'
    | '/legal/location-weather'
    | '/legal/privacy'
    | '/legal/terms'
    | '/o/$slug'
    | '/u/$handle'
    | '/legal/'
    | '/admin/catalog'
    | '/admin/moderation'
    | '/closet/$id'
    | '/closet/new'
    | '/closet/'
    | '/admin/catalog/imports'
    | '/closet/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/feed'
    | '/generate'
    | '/home'
    | '/inspo'
    | '/profile'
    | '/saved'
    | '/scents'
    | '/shop'
    | '/swipe'
    | '/taste'
    | '/auth/reset-password'
    | '/legal/acceptable-use'
    | '/legal/account-deletion'
    | '/legal/affiliate-disclosure'
    | '/legal/ai-image-processing'
    | '/legal/beta-notice'
    | '/legal/community-guidelines'
    | '/legal/copyright'
    | '/legal/location-weather'
    | '/legal/privacy'
    | '/legal/terms'
    | '/o/$slug'
    | '/u/$handle'
    | '/legal'
    | '/admin/catalog'
    | '/admin/moderation'
    | '/closet/$id'
    | '/closet/new'
    | '/closet'
    | '/admin/catalog/imports'
    | '/closet/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/legal'
    | '/onboarding'
    | '/_authenticated/feed'
    | '/_authenticated/generate'
    | '/_authenticated/home'
    | '/_authenticated/inspo'
    | '/_authenticated/profile'
    | '/_authenticated/saved'
    | '/_authenticated/scents'
    | '/_authenticated/shop'
    | '/_authenticated/swipe'
    | '/_authenticated/taste'
    | '/auth_/reset-password'
    | '/legal/acceptable-use'
    | '/legal/account-deletion'
    | '/legal/affiliate-disclosure'
    | '/legal/ai-image-processing'
    | '/legal/beta-notice'
    | '/legal/community-guidelines'
    | '/legal/copyright'
    | '/legal/location-weather'
    | '/legal/privacy'
    | '/legal/terms'
    | '/o/$slug'
    | '/u/$handle'
    | '/legal/'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/closet/$id'
    | '/_authenticated/closet/new'
    | '/_authenticated/closet/'
    | '/_authenticated/admin/catalog_/imports'
    | '/_authenticated/closet/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LegalRoute: typeof LegalRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  OSlugRoute: typeof OSlugRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$slug': {
      id: '/o/$slug'
      path: '/o/$slug'
      fullPath: '/o/$slug'
      preLoaderRoute: typeof OSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/location-weather': {
      id: '/legal/location-weather'
      path: '/location-weather'
      fullPath: '/legal/location-weather'
      preLoaderRoute: typeof LegalLocationWeatherRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/copyright': {
      id: '/legal/copyright'
      path: '/copyright'
      fullPath: '/legal/copyright'
      preLoaderRoute: typeof LegalCopyrightRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/community-guidelines': {
      id: '/legal/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/legal/community-guidelines'
      preLoaderRoute: typeof LegalCommunityGuidelinesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/beta-notice': {
      id: '/legal/beta-notice'
      path: '/beta-notice'
      fullPath: '/legal/beta-notice'
      preLoaderRoute: typeof LegalBetaNoticeRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/ai-image-processing': {
      id: '/legal/ai-image-processing'
      path: '/ai-image-processing'
      fullPath: '/legal/ai-image-processing'
      preLoaderRoute: typeof LegalAiImageProcessingRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/affiliate-disclosure': {
      id: '/legal/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/legal/affiliate-disclosure'
      preLoaderRoute: typeof LegalAffiliateDisclosureRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/account-deletion': {
      id: '/legal/account-deletion'
      path: '/account-deletion'
      fullPath: '/legal/account-deletion'
      preLoaderRoute: typeof LegalAccountDeletionRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof LegalRoute
    }
    '/auth_/reset-password': {
      id: '/auth_/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/taste': {
      id: '/_authenticated/taste'
      path: '/taste'
      fullPath: '/taste'
      preLoaderRoute: typeof AuthenticatedTasteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/swipe': {
      id: '/_authenticated/swipe'
      path: '/swipe'
      fullPath: '/swipe'
      preLoaderRoute: typeof AuthenticatedSwipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scents': {
      id: '/_authenticated/scents'
      path: '/scents'
      fullPath: '/scents'
      preLoaderRoute: typeof AuthenticatedScentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspo': {
      id: '/_authenticated/inspo'
      path: '/inspo'
      fullPath: '/inspo'
      preLoaderRoute: typeof AuthenticatedInspoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closet/': {
      id: '/_authenticated/closet/'
      path: '/closet'
      fullPath: '/closet/'
      preLoaderRoute: typeof AuthenticatedClosetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closet/new': {
      id: '/_authenticated/closet/new'
      path: '/closet/new'
      fullPath: '/closet/new'
      preLoaderRoute: typeof AuthenticatedClosetNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closet/$id': {
      id: '/_authenticated/closet/$id'
      path: '/closet/$id'
      fullPath: '/closet/$id'
      preLoaderRoute: typeof AuthenticatedClosetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closet/$id/edit': {
      id: '/_authenticated/closet/$id/edit'
      path: '/edit'
      fullPath: '/closet/$id/edit'
      preLoaderRoute: typeof AuthenticatedClosetIdEditRouteImport
      parentRoute: typeof AuthenticatedClosetIdRoute
    }
    '/_authenticated/admin/catalog_/imports': {
      id: '/_authenticated/admin/catalog_/imports'
      path: '/admin/catalog/imports'
      fullPath: '/admin/catalog/imports'
      preLoaderRoute: typeof AuthenticatedAdminCatalogImportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedClosetIdRouteChildren {
  AuthenticatedClosetIdEditRoute: typeof AuthenticatedClosetIdEditRoute
}

const AuthenticatedClosetIdRouteChildren: AuthenticatedClosetIdRouteChildren = {
  AuthenticatedClosetIdEditRoute: AuthenticatedClosetIdEditRoute,
}

const AuthenticatedClosetIdRouteWithChildren =
  AuthenticatedClosetIdRoute._addFileChildren(
    AuthenticatedClosetIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInspoRoute: typeof AuthenticatedInspoRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedScentsRoute: typeof AuthenticatedScentsRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedSwipeRoute: typeof AuthenticatedSwipeRoute
  AuthenticatedTasteRoute: typeof AuthenticatedTasteRoute
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedClosetIdRoute: typeof AuthenticatedClosetIdRouteWithChildren
  AuthenticatedClosetNewRoute: typeof AuthenticatedClosetNewRoute
  AuthenticatedClosetIndexRoute: typeof AuthenticatedClosetIndexRoute
  AuthenticatedAdminCatalogImportsRoute: typeof AuthenticatedAdminCatalogImportsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInspoRoute: AuthenticatedInspoRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedScentsRoute: AuthenticatedScentsRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedSwipeRoute: AuthenticatedSwipeRoute,
  AuthenticatedTasteRoute: AuthenticatedTasteRoute,
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedClosetIdRoute: AuthenticatedClosetIdRouteWithChildren,
  AuthenticatedClosetNewRoute: AuthenticatedClosetNewRoute,
  AuthenticatedClosetIndexRoute: AuthenticatedClosetIndexRoute,
  AuthenticatedAdminCatalogImportsRoute: AuthenticatedAdminCatalogImportsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LegalRouteChildren {
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalAccountDeletionRoute: typeof LegalAccountDeletionRoute
  LegalAffiliateDisclosureRoute: typeof LegalAffiliateDisclosureRoute
  LegalAiImageProcessingRoute: typeof LegalAiImageProcessingRoute
  LegalBetaNoticeRoute: typeof LegalBetaNoticeRoute
  LegalCommunityGuidelinesRoute: typeof LegalCommunityGuidelinesRoute
  LegalCopyrightRoute: typeof LegalCopyrightRoute
  LegalLocationWeatherRoute: typeof LegalLocationWeatherRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalAccountDeletionRoute: LegalAccountDeletionRoute,
  LegalAffiliateDisclosureRoute: LegalAffiliateDisclosureRoute,
  LegalAiImageProcessingRoute: LegalAiImageProcessingRoute,
  LegalBetaNoticeRoute: LegalBetaNoticeRoute,
  LegalCommunityGuidelinesRoute: LegalCommunityGuidelinesRoute,
  LegalCopyrightRoute: LegalCopyrightRoute,
  LegalLocationWeatherRoute: LegalLocationWeatherRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LegalRoute: LegalRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  OSlugRoute: OSlugRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
